### ISSUE TITLE
优化一下

### ISSUE THREAD

**Issue by lloyd18** [lisaac/luci-app-diskman#11]
![00](https://user-images.githubusercontent.com/10294460/73859576-38d3ce80-4875-11ea-80c3-bc52e1a522ba.jpg)
谢谢你的项目
在此提个小建议
显示优化一下，挂载选项那里太长了，可以选择隐藏部分信息，不想要下面的滚动条，而且卸载操作也不方便

**Comment by lloyd18** [comment]
![000](https://user-images.githubusercontent.com/10294460/73859689-6751a980-4875-11ea-917d-c8aa777547c3.jpg)
这部分未汉化

**Comment by lisaac** [comment]
已调整并提交
