### ISSUE TITLE
打扰一下，关于改变分类

### ISSUE THREAD

**Issue by lloyd18** [lisaac/luci-app-diskman#13]
如果我想把插件移到NAS分类下，要修改哪些东西？
尝试修改图上的system改成nas能改变分类 但部分信息不显示和操作报错
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/73931264-f52fa200-4912-11ea-91c2-cc7a459de961.jpg)

**Comment by lloyd18** [comment]
还有就是很多信息没有 序列号 SATA版本 温度 监控 和状态，也不知道为点啥
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/73932373-27da9a00-4915-11ea-9418-85712c9975c3.jpg)

**Comment by lisaac** [comment]
1.改变分类，首先需要在 controller 中修改，然后在所有关于请求及跳转的路由中也需要修改
2.一般 usb 设备是不支持 S.M.A.R.T 信息检测的，所以无法读取

**Comment by lloyd18** [comment]
> 1.改变分类，首先需要在 controller 中修改，然后在所有关于请求及跳转的路由中也需要修改
> 2.一般 usb 设备是不支持 S.M.A.R.T 信息检测的，所以无法读取

谢谢回复，好像很复杂，搞不来，放弃了
