### ISSUE TITLE
最新源码无汉化

### ISSUE THREAD

**Issue by zxlhhyccc** [lisaac/luci-app-diskman#15]
![image](https://user-images.githubusercontent.com/45259624/75117047-247f3680-56a9-11ea-9584-12765bf7b095.png)
![image](https://user-images.githubusercontent.com/45259624/75117061-45478c00-56a9-11ea-8ce8-7477ffc9ea12.png)

**Comment by lisaac** [comment]
汉化是makefle问题，你说不能工作，请给下你的环境

**Comment by zxlhhyccc** [comment]
> 汉化是makefle问题，你说不能工作，请给下你的环境

不好意思可以运行，因为不能修改主题就没更正，就是不能汉化

**Comment by lisaac** [comment]
用老版本makefile
或者直接安装ipk
最近有些事情，空的时候再改
