### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-app-diskman#2]
Collected errors:
 * check_data_file_clashes: Package luci-app-dockerman wants to install file /home/deepin/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/lua/luci/view/cbi/inlinebutton.htm
	But that file is already provided by package  * luci-app-diskman
 * check_data_file_clashes: Package luci-app-dockerman wants to install file /home/deepin/lede/build_dir/target-x86_64_musl/root-x86/usr/lib/lua/luci/view/cbi/xsimpleform.htm
	But that file is already provided by package  * luci-app-diskman
 * opkg_install_cmd: Cannot install package luci-app-dockerman.

**Comment by lisaac** [comment]
与  luci-app-dockerman 自定义 view 冲突
v0.1.2-beta 已修复
