### ISSUE TITLE
我更新源码过后编译make menuconfig后有报错

### ISSUE THREAD

**Issue by yangsongli** [lisaac/luci-app-diskman#21]
lean源码 错误如图
![image](https://user-images.githubusercontent.com/52395039/76161902-ac1d7880-6172-11ea-9271-fbd9f685b59c.png)

**Comment by lisaac** [comment]
kmod-md选择问题，把 kmod-md-mod 加上吧

**Comment by lisaac** [comment]
已提交，试试最新的Makefile

**Comment by yangsongli** [comment]
已解决

**Comment by yangsongli** [comment]
最新的Makefile已解决
