### ISSUE TITLE
Bad translation of 3 words

### ISSUE THREAD

**Issue by IceG2020** [lisaac/luci-app-diskman#22]
Hi :)
Recently I noticed that I do not have a translation of the phrase "Free Space" in the "Partition info" window, I added a translation to the file "diskman.po" but nothing changes why, I have no translation for "Free Space" and another translation for "Used" and "Usage". What could be wrong? :)
Regards
IceG

**Comment by lisaac** [comment]
Is it work now?

**Comment by IceG2020** [comment]
![](https://s6.ifotos.pl/img/111png_qawnxpx.png)

Hi :)
Unfortunately, it still displays differently than it is in the translation file .. strange ..

**Comment by lisaac** [comment]
I believe that you have another luci app has translated these 3 word, then luci use that translate word to display on diskman, please check.
Thanks

**Comment by IceG2020** [comment]
From all applications installed on my router only luci-app-opkg has the phrase "Free space:" and it is translated correctly.
Regards

**Comment by lisaac** [comment]
It's weird, since the another lanuage is worked.
I still believe there is another app has translated it.
Simultaneously, we using 'Free Space', not 'Free space:'

Please check it again.

**Comment by IceG2020** [comment]
Everything is ok, I cleaned the compilation and the new build image has everything beautifully translated.
Regards
IceG
