### ISSUE TITLE
磁盘容量条显示特别长

### ISSUE THREAD

**Issue by jwf8280031** [lisaac/luci-app-diskman#25]
![Snipaste_2020-03-16_18-42-33](https://user-images.githubusercontent.com/51179079/77550023-8e2e7280-6eeb-11ea-9d41-4720fc29d3fa.png)
您好！我用lean源码编译了您这个插件，但是这个磁盘容量条显示特别长。

**Comment by lisaac** [comment]
用的什么浏览器？
建议换个浏览器试试
