### ISSUE TITLE
openwrt 19.07 smartdetail获取不到数据

### ISSUE THREAD

**Issue by garypang13** [lisaac/luci-app-diskman#29]
![2020-4-8 19-22-17](https://user-images.githubusercontent.com/48883331/78778723-4ff68000-79ce-11ea-87b0-54b21e7da248.png)
直接访问/admin/system/diskman/smartattr/sdb能获取到json数据,但是这个页面获取不到
smart_detail.html中引入的xhr.js在luci 19.07中已经被luci.js替代了,但是改成luci.js还是不行.

**Comment by lisaac** [comment]
已经修改了一下，请测试一下

**Comment by garypang13** [comment]
可以了,非常感谢!
