### ISSUE TITLE
x86 platform system hard disk displays abnormally

### ISSUE THREAD

**Issue by zdz2019** [lisaac/luci-app-diskman#3]
x86 platform system partition is displayed abnormally.
![Snipaste_2020-01-06_10-58-55](https://user-images.githubusercontent.com/50648881/71792464-cb653000-3073-11ea-8157-21437966b696.png)
![Snipaste_2020-01-06_11-00-06](https://user-images.githubusercontent.com/50648881/71792465-cc965d00-3073-11ea-8642-f8c9e055c82b.png)

Another way is displayed normally, provide documents for reference.
[luci-mod-admin-full.zip](https://github.com/lisaac/luci-app-diskman/files/4024546/luci-mod-admin-full.zip)

**Comment by lisaac** [comment]
是的，这是个问题，也不是个问题，严格来讲这其实是正常的，只是不那么优雅

导致现在这种情况原因是，显示的分区宽度是严格按照分区(包括未分配)比例进行调整的。有些分区占比特别小，有可能看不到，但它是确实存在的，光标定位上会有显示

另外解释下，下图中看起来比较优雅，但比例是失衡的，分区很多的情况下也可能有变形，而且此方案是用的 table 布局，而新 luci 采用 div 模拟 table

所以这是个取舍问题，可能下次把这些细节细化一下
