### ISSUE TITLE
建议“分区表图”部分，加入支持暗黑主题的颜色/ Suggest to add system/theme dark mode detect for partition table part

### ISSUE THREAD

**Issue by xylz0928** [lisaac/luci-app-diskman#38]
https://github.com/lisaac/luci-app-diskman/blob/master/applications/luci-app-diskman/luasrc/view/diskman/disk_info.htm#L4
![iShot2021-03-30 12 53 35](https://user-images.githubusercontent.com/34766756/112936647-c567dd00-9158-11eb-8431-a32337084a08.png)

the backgorund color of this part(partition table) is showing well on light themes(text most using dark colors).
该位置设计的“分区表图”部分的背景色，在各大浅色主题下显示正常，

but cannot display clearly on any dark theme (text most using light colors), the text will be mixed with background color.
但在各种暗黑主题下（文字偏白色），文字与背景色会显示看不清。

so suggest:
故建议：

1. Add css to detect system/theme dark mode, then show different background color on this part.
     1) 加入自动识别系统暗黑模式来对应显示不同的背景色。

2. Or, lock the color of texts in this part, set as #000000 or other dark texts.
     2) 或，锁定该部分文字的颜色显示，固定为#000000或其他偏黑色
See / 见，    https://github.com/xylz0928/luci-app-diskman/tree/patch-1

**Comment by lisaac** [comment]
提交一个PR吧

**Comment by xylz0928** [comment]
> 提交一个PR吧

#39
