### ISSUE TITLE
格式化列表没有exfat ntfs等格式。

### ISSUE THREAD

**Issue by lhuanyun** [lisaac/luci-app-diskman#61]
是不是缺少什么依赖？
我的可操作格式只有这几个。
平台是mipsel![image](https://user-images.githubusercontent.com/20707383/206950858-a6f60c03-5b00-47b2-bd81-7000f5a22598.png)

**Comment by lhuanyun** [comment]
有人吗…

**Comment by lisaac** [comment]
ntfs support: ntfs-3g
exfat support: exfatprogs
