### ISSUE TITLE
随固件编译，luci里没有界面

### ISSUE THREAD

**Issue by Speechless22** [lisaac/luci-app-diskman#67]
![image](https://user-images.githubusercontent.com/61347609/229267356-fc631a2b-1e01-4379-9621-5e3aaeea58e2.png)
依赖都正常

**Comment by Speechless22** [comment]
前两天直接装你的ipk还能用，编到固件里就没界面了。从官方master分支编译

**Comment by muink** [comment]
应该是因为没有写下面两个文件, 现在openwrt官方源21.02开始, 用标准编译方式, 不写 `luci/menu.d` 是没有界面的
暂时的解决方法是卸载新版用老版本升级上来
`/usr/share/luci/menu.d/luci-app-diskman.json`
`/usr/share/rpcd/acl.d/luci-app-tinyproxy.json`

**Comment by muink** [comment]
重现了下错误, 是浏览器缓存的问题, 开启 `F12` 开发者工具, 在分页 `Network` 里把 `Disable cache` 勾选上刷新页面就好了
![1](https://user-images.githubusercontent.com/7929014/233778103-e8ddcb42-6bbe-417d-8d7a-c66d5bb0781f.png)

**Comment by muink** [comment]
@wazzx 我这边已经无法复现问题了, 应该是正常了
你看看会不会是 `luci-compat` `luci-lib-ipkg` 这两个包没装
或者用我这边编译的试试 [luci-app-diskman_v0.2.12_all.ipk](https://fantastic-packages.github.io/packages/releases/21.02/packages/x86_64/packages/luci-app-diskman_v0.2.12_all.ipk)

**Comment by muink** [comment]
2KB确实不正常, 可能是编译的步骤出了什么问题, 我这里编译出来是 21KB
你可以下载上个对话里的ipk看看, 是能正常用的
![1](https://user-images.githubusercontent.com/7929014/233784834-3495ae33-b768-435d-8f2f-f05ab64a3d6d.png)

**Comment by muink** [comment]
luci-app是全平台通用, 你可以下载来直接用

**Comment by muink** [comment]
卸载掉新版本装[老版本](https://github.com/lisaac/luci-app-diskman/releases/tag/v0.2.11)试试呢
界面会有吗, 有的话再时间安装新版看看

**Comment by Nelocompne** [comment]
> ![1](https://user-images.githubusercontent.com/7929014/233783727-77fcbbb7-445f-4cd3-86d3-98c323afcf4a.png)
> 
> @wazzx 我这边已经无法复现问题了, 应该是正常了 你看看会不会是 `luci-compat` `luci-lib-ipkg` 这两个包没装 或者用我这边编译的试试 [luci-app-diskman_v0.2.12_all.ipk](https://fantastic-packages.github.io/packages/releases/21.02/packages/x86_64/packages/luci-app-diskman_v0.2.12_all.ipk) v0.2.13版本还在编译, 就修复了个没有编译语言文件的问题 估计再一两个小时自动推送到 https://fantastic-packages.github.io/packages

我的固件也是无法看到按钮，但是装上  `luci-compat` `luci-lib-ipkg`  两个包后就能看到了，这对我很有帮助！
