### ISSUE TITLE
Wrong "code"

### ISSUE THREAD

**Issue by obsy** [lisaac/luci-app-diskman#7]
Hi, see line
https://github.com/lisaac/luci-app-diskman/blob/ae51f6f54b73ea041aeafbdb341efed793bf44b5/luasrc/model/cbi/diskman/partition.lua#L314

and

https://github.com/lisaac/luci-app-diskman/blob/ae51f6f54b73ea041aeafbdb341efed793bf44b5/luasrc/model/cbi/diskman/partition.lua#L254

the code is incorrect, in other languages ​​the button text is not "new" and "delete", but has been translated by luci (in ex: Polish: "new" and "delete").

**Comment by lisaac** [comment]
Hi Cezary Jackiewicz,
Thanks for your information, this is a bug and has been fixed in last commit!
