### ISSUE TITLE
今天git pull源码编译后，使用出报错，前几天的源码没这个问题

### ISSUE THREAD

**Issue by lllrrr** [lisaac/luci-app-diskman#9]
Failed to execute cbi dispatcher target for entry '/admin/system/diskman/disks'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/diskman.lua:270: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
	[C]: in function 'match'
	/usr/lib/lua/luci/model/diskman.lua:270: in function 'get_mount_points'
	/usr/lib/lua/luci/model/cbi/diskman/disks.lua:158: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:976: in function </usr/lib/lua/luci/dispatcher.lua:971>

**Comment by IceG2020** [comment]
`/usr/lib/lua/luci/model/diskman.lua:270: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
	[C]: in function 'match'
	/usr/lib/lua/luci/model/diskman.lua:270: in function 'get_mount_points'
	/usr/lib/lua/luci/model/cbi/diskman/disks.lua:158: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1369: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:929: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:902: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:440: in function </usr/lib/lua/luci/dispatcher.lua:439>`
